image: androidsdk/android-31

pipelines:
  branches:
    development:
      - step:
          name: Build Debug Application
          caches:
            - gradle
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
      - step:
          name: upload
          deployment: test
          script:
            - curl -v -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"app/build/outputs/apk/debug/app-debug.apk"
    master:
      - step:
          name: Build Prod Application
          caches:
            - gradle
          script:
            - ./gradlew assembleRelease
          artifacts:
            - app/build/outputs/**
      - step:
          name: upload
          deployment: production
          script:
            - curl -v -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"app/build/outputs/apk/release/app-release-unsigned.apk"
  default:
      - step:
          name: Build Debug Application
          caches:
            - gradle
          script:
            - ./gradlew assembleDebug
          artifacts:
            - app/build/outputs/**
  